### ISSUE TITLE
[Podman 1.6.4] Problem running via systemd after upgrade podman and slirp4netns on CentOS 8

### ISSUE THREAD

**Issue by decosvaldo** [rootless-containers/slirp4netns#174] opened 2020-03-09 20:03 UTC
Hi everybody.

I'm using podman in CentOS 8, which was recently upgraded to the version 1.6.4. After the upgrade, I'm facing an issue when starting the container via Systemd with the detach option.

I'm using rootless containers and one of my systemd files are bellow:

`[Unit]
Description=Site Lnes
[Service]
Restart=on-failure
ExecStartPre=/usr/bin/rm -f /home/web/.local/share/containers/storage/overlay-containers/lnes/lnes.pid /home/web/.local/share/containers/storage/overlay-containers/lnes/lnes.cid
ExecStart=/usr/bin/podman run --conmon-pidfile /home/web/.local/share/containers/storage/overlay-containers/lnes/lnes.pid --cidfile /home/web/.local/share/containers/storage/overlay-containers/lnes/lnes.cid -v /home/web/lnes/src:/var/www/html:Z -v /home/web/lnes/config/nginx.conf:/etc/nginx/nginx.conf:Z -v /home/web/lnes/config/phpcustom.ini:/etc/php5/conf.d/custom.ini:Z -v /home/web/lnes/config/php-fpm.conf:/etc/php5/fpm.d/www.conf:Z -p 2001:8080 --userns=keep-id -d iq/lnes
ExecStop=/usr/bin/sh -c "podman rm -f `cat /home/web/.local/share/containers/storage/overlay-containers/lnes/lnes.cid`" ; rm -f /home/web/.local/share/containers/storage/overlay-containers/lnes/lnes.cid
KillMode=none
Type=forking
PIDFile=/home/web/.local/share/containers/storage/overlay-containers/lnes/lnes.pid
User=web
Group=web
[Install]
WantedBy=multi-user.target`

Everything was working correctly. But now, when running via systemd, I receive an error when starting and this log information:

`Job for lnes.service failed because the control process exited with error code.
See "systemctl status lnes.service" and "journalctl -xe" for details.

Mar 03 15:43:04 messenger.iqm.unicamp.br podman[13187]: Error: error from slirp4netns while setting up port redirection: map[desc:bad request: add_hostfwd: slirp_add_hostfwd fa..`

If I remove the -d (--detach) option from the systemd file, everything works perfectly, but I don't have the same result running podman run manually, which works both ways (with or without the -d option). The systemd method was working perfectly with the 1.4 version of podman.

`[root@messenger andre.paiz]# systemctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy
[root@messenger andre.paiz]# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 7a4f0dd7b20a3d4bf9ef3e5cbfac05606b08eac0'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 7099490304
  MemTotal: 8192372736
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8497655808
  SwapTotal: 8497655808
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: messenger.iqm.unicamp.br
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: false
  uptime: 24h 23m 46.8s (Approximately 1.00 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

[root@messenger andre.paiz]# slirp4netns --version
slirp4netns version 0.4.2+dev
commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4`

Any thoughts?

**Comment by AkihiroSuda** [comment] 2020-03-10 01:42
Exposing port number < 1024, or port number conflict?

**Comment by decosvaldo** [comment] 2020-03-10 11:54
> Exposing port number < 1024, or port number conflict?

Exposing 8080 (as showing in the systemd config file) and I'm redirecting traffic from port 2001 to it. This configuration was working before the last upgrade.

**Comment by AkihiroSuda** [comment] 2020-03-10 12:05
Maybe better to open an issue in Podman repo?
Maybe related to SELinux stuff?

**Comment by AkihiroSuda** [comment] 2020-03-10 12:06
cc @giuseppe @rhatdan

**Comment by decosvaldo** [comment] 2020-03-10 12:25
> Maybe better to open an issue in Podman repo?
> Maybe related to SELinux stuff?

I have the same case registered with the Podman repo and waiting for reply. It was working with SELinux, but I'm testing now without it to see if anything changed with Systemd and SELinux and I will let you know.

**Comment by rhatdan** [comment] 2020-03-10 13:34
@vrothberg, is this something you recently fixed?

**Comment by vrothberg** [comment] 2020-03-10 13:37
> @vrothberg, is this something you recently fixed?

No. `error from slirp4netns while setting up port redirection` seems like a slirp4netns bug rather than a Podman issue.

**Comment by AkihiroSuda** [comment] 2020-05-27 10:13
Is this still an issue?

> No. error from slirp4netns while setting up port redirection seems like a slirp4netns bug rather than a Podman issue.

If Podman is sending a wrong request to slirp4netns, the issue is on Podman side.

**Comment by AkihiroSuda** [comment] 2020-07-07 09:45
Closing, but feel free to reopen

**Closed by AkihiroSuda** 2020-07-07 09:45 UTC
Labels: question
