### ISSUE TITLE
Can't install rootless docker due to bug on slirp4netns

### ISSUE THREAD

**Issue by schklom** [rootless-containers/slirp4netns#255] opened 2021-02-19 03:58 UTC
Hi guys,

I hope I'm in the correct repo to ask this ^^

I'm trying to install rootless docker on my Raspberry Pi 4 with Debian Buster on it. Details:
```
$ uname -a
Linux schklom 5.10.0-3-arm64 #1 SMP Debian 5.10.13-1 (2021-02-06) aarch64 GNU/Linux

$ slirp4netns -v
slirp4netns version 1.0.1
commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
libslirp: 4.4.0
```

Now I have a bug that I can't solve myself, so I'm hoping someone here can help :)

The `docker.service` attempts to execute this on `ExecStart`, but fails
```
$ sh /home/schklom/bin/dockerd-rootless.sh
+ [ -w /run/user/1001 ]
+ [ -w /home/schklom/ ]
+ rootlesskit=
+ which docker-rootlesskit
+ which rootlesskit
+ rootlesskit=rootlesskit
+ break
+ [ -z rootlesskit ]
+ :
+ :
+ : builtin
+ : auto
+ : auto
+ net=
+ mtu=
+ [ -z ]
+ which slirp4netns
+ slirp4netns --help
+ grep -qw -- --netns-type
+ net=slirp4netns
+ [ -z ]
+ mtu=65520
+ [ -z slirp4netns ]
+ [ -z 65520 ]
+ [ -z ]
+ _DOCKERD_ROOTLESS_CHILD=1
+ export _DOCKERD_ROOTLESS_CHILD
+ exec rootlesskit --net=slirp4netns --mtu=65520 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /home/schklom/bin/dockerd-rootless.sh
[rootlesskit:parent] error: failed to setup network &{logWriter:0x400008dec0 binary:slirp4netns mtu:65520 ipnet:<nil> disableHostLoopback:true apiSocketPath: enableSandbox:true enableSeccomp:true ifname:tap0}: waiting for ready fd (/usr/bin/slirp4netns --mtu 65520 -r 3 --disable-host-loopback --enable-sandbox --enable-seccomp 1442 tap0): slirp4netns failed
[rootlesskit:child ] error: parsing message from fd 3: EOF
```

Does the problem come from slirp4netns ? Or from Docker ?

Does anyone have a clue what's happening ?

**Comment by AkihiroSuda** [comment] 2021-02-19 07:57
duplicate of https://github.com/moby/moby/issues/42048

**Closed by AkihiroSuda** 2021-02-19 07:57 UTC
