### ISSUE TITLE
slirp4netns: endless loop or huge cpu usage (related to UDP?)

### ISSUE THREAD

**Issue by disaster123** [rootless-containers/slirp4netns#227] opened 2020-10-05 09:10 UTC
Hello,

while using jitsi with podman i'm seeing slirp4netns getting stuck constantly at 100% cpu no longer accepting connections.

Command started by podman:
```
/usr/bin/slirp4netns --disable-host-loopback --mtu 65520 --enable-sandbox --enable-seccomp --api-socket /run/user/1000/libpod/tmp/d60771fb7b575a35f90f9c8525578df771dd3812aa14314b31d0a659b2e91c6b.net -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/cni-e592fe0c-c16c-b9ca-a989-cea8c63152be tap0
```

slirp4netns binary is this one: `https://github.com/rootless-containers/slirp4netns/releases/download/v1.1.4/slirp4netns-x86_64`

gdb shows (i don't have any debug symbols for the build):
```
(gdb) bt
#0  0x00000000004ecf97 in ?? ()
#1  0x000000000044dcf6 in ?? ()
#2  0x00007fff9688e350 in ?? ()
#3  0x0000000000b7fd00 in ?? ()
#4  0x00007fff9688e3a0 in ?? ()
#5  0x0000000000b7e3f0 in ?? ()
#6  0x0000000000b84f28 in ?? ()
#7  0x0000000000ba8790 in ?? ()
#8  0x0000000000b7e3f0 in ?? ()
#9  0x0000000000ba8800 in ?? ()
#10 0x00007fff9688e370 in ?? ()
#11 0x000000000045e55c in ?? ()
#12 0x0000000000ba8800 in ?? ()
#13 0x0000000000ba8790 in ?? ()
#14 0x00007fff9688e5b0 in ?? ()
#15 0x00000000004514e0 in ?? ()
#16 0x0000000100ba8790 in ?? ()
#17 0x0000000000000000 in ?? ()
```

strace shows:
```
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=563842199}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=563886704}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=563931690}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564033383}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564124767}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564170634}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564213966}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564302274}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564374191}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564408837}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564448211}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564533874}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564606082}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564653432}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564697726}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564787697}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564858442}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564896244}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=564932733}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565085363}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565180463}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565230809}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565282268}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565398739}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565497907}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565545228}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565597166}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565726361}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565853063}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565908568}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=565966418}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566108508}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566228335}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566287689}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566369464}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566502007}) = 0
ioctl(9, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566656831}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566709711}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566761750}) = 0
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
clock_gettime(CLOCK_MONOTONIC, {tv_sec=1084528, tv_nsec=566891958}) = 0
```

I can only fix this by restartin the whole container.

Stefan

**Comment by AkihiroSuda** [comment] 2020-10-05 21:11
Could you provide full reproducer?

**Comment by AkihiroSuda** [comment] 2020-10-05 21:12
> gdb 

If you compile slirp4netns from source, maybe you will get symbols

**Comment by AkihiroSuda** [comment] 2020-10-05 21:17
It seems this loop is iterating too much without any packet?

https://github.com/rootless-containers/slirp4netns/blob/676792204708ce10c7553000dcf293a79db6277a/slirp4netns.c#L37

cc @giuseppe

**Comment by disaster123** [comment] 2020-10-06 06:02
> Could you provide full reproducer?

no it happens out of nothing - but on a regular basis (two times a week)

> > gdb
> 
> If you compile slirp4netns from source, maybe you will get symbols

Last time i did it wasn't working - that the reason i'm using the provided static binaries.

**Comment by giuseppe** [comment] 2020-10-07 11:34
something seems wrong with FIONREAD reporting 0 bytes after a SLIRP_POLL_IN event:

```
poll([{fd=7, events=POLLIN|POLLHUP}, {fd=3, events=POLLHUP}, {fd=5, events=POLLIN|POLLHUP}, {fd=10, events=POLLIN|POLLERR|POLLHUP}, {fd=8, events=POLLIN|POLLERR|POLLHUP}, {fd=9, events=POLLIN|POLLERR|POLLHUP}], 6, 499) = 1 ([{fd=9, revents=POLLIN}])
ioctl(9, FIONREAD, [0])                 = 0
```

I am not sure how this could happen, and if libslirp could avoid using FIOREAD.

**Comment by AkihiroSuda** [comment] 2020-10-07 11:42
Thanks @giuseppe 

Seems somehow related to UDP? https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.3.1/src/socket.c#L532

@disaster123 Does jitsi heavily uses UDP? Do you think the packet in the problem is coming from jitsi or DNS?

**Comment by disaster123** [comment] 2020-10-07 11:55
@AkihiroSuda yes it uses heavily UDP

**Comment by AkihiroSuda** [comment] 2020-10-07 12:18
What is the port forwarder? RootlessKit (default in the recent Podman), or slirp4netns (non-default)?

**Comment by disaster123** [comment] 2020-10-07 12:23
slirp4netns as RootlessKit does not keep the source ip

**Comment by disaster123** [comment] 2020-10-13 20:22
@AkihiroSuda any news or ideas?

**Comment by AkihiroSuda** [comment] 2020-10-15 14:10
@elmarco Do you know whether a similar issue exists in qemu?

**Comment by elmarco** [comment] 2020-10-15 14:16
@AkihiroSuda no, I haven't heard of such kind of issue

**Comment by disaster123** [comment] 2020-10-19 06:01
@AkihiroSuda is there any quick fix or hack i might try? currently i need to restart the pod every 2 or 3 days.

**Comment by AkihiroSuda** [comment] 2020-10-19 06:10
Bypassing slirp4netns is under development ( https://github.com/rootless-containers/bypass4netns ), but still early POC and requires very new kernel.

The most realistic workaround is `--net=host`, though it is insecure.

**Comment by disaster123** [comment] 2020-10-19 06:14
Both don't look like a real workaround. Insecurity isn't a good idea - than we could use docker anyway.  Isn't there a quick fix to leave the loop under a certain condition?

**Comment by disaster123** [comment] 2020-10-19 06:43
@AkihiroSuda isn't this related to: https://stackoverflow.com/questions/16995766/what-does-fionread-of-udp-datagram-sockets-return see first answer

**Comment by giuseppe** [comment] 2020-10-19 15:22
I wonder if we can still attempt a non blocking read when fionread returns 0 to avoid the endless loop

**Comment by AkihiroSuda** [comment] 2020-10-19 16:10
:+1: But we might need a repro to verify that.

**Comment by disaster123** [comment] 2020-10-19 16:13
I can verify with running the modified code?

**Comment by disaster123** [comment] 2020-11-03 10:17
Anything i can test? try or patch?

**Comment by giuseppe** [comment] 2020-11-03 10:44
I'd just try libslirp with something like:

```diff
diff --git a/src/socket.c b/src/socket.c
index 3fbb873..e9ad97d 100644
--- a/src/socket.c
+++ b/src/socket.c
@@ -535,6 +535,8 @@ void sorecvfrom(struct socket *so)
             return;
         }
         if (n == 0) {
+            char b[16];
+            recvfrom(so->s, b, sizeof(b), 0, (struct sockaddr *)&addr, &addrlen);
             return;
         }
```

**Comment by disaster123** [comment] 2020-11-03 13:14
Thanks! I rebuild slirp4netns linked statically against a local patched version of libslirp. Will report back if this helps.

**Comment by disaster123** [comment] 2020-11-06 14:39
@giuseppe this really seems to fix the bug. At least it hadn't happened again. Will still wait some more days.

**Comment by AkihiroSuda** [comment] 2020-11-16 09:13
@disaster123 Is it working well?

**Comment by disaster123** [comment] 2020-11-16 09:20
Yes - it's working fine!!

**Comment by AkihiroSuda** [comment] 2020-11-16 09:43
Thanks @disaster123 @giuseppe 

@giuseppe Could you submit your patch to libslirp upstream?

**Comment by giuseppe** [comment] 2020-11-16 16:01
MR here: https://gitlab.freedesktop.org/slirp/libslirp/-/merge_requests/55

**Comment by AkihiroSuda** [comment] 2020-11-16 16:13
Thank you!

**Comment by sthibaul** [comment] 2020-11-16 17:47
Mmm, shouldn't we just drop the if (n==0)  { return; } stanza?
I mean, empty UDP packets may really have some meaning, so we should probably not just drop them.
Could you try removing these three lines instead of eating the packet?

**Comment by AkihiroSuda** [comment] 2020-11-25 08:34
@disaster123 @giuseppe WDYT about @sthibaul 's comment?

**Comment by giuseppe** [comment] 2020-11-25 09:13
I am fine with it, @disaster123 could you give it a try? :-)

**Comment by disaster123** [comment] 2020-11-25 09:45
Yes i could i was waiting for an OK to test from you ;-)

**Comment by disaster123** [comment] 2020-12-01 09:29
Seems this works as well and also fixes the problem.

**Comment by giuseppe** [comment] 2020-12-01 10:33
thanks for trying it out.  I've updated the MR

**Comment by AkihiroSuda** [comment] 2020-12-02 06:40
Thanks all, the MR seems merged now :+1:

@elmarco @sthibaul Can we get a new tagged release of libslirp?

**Closed** 2020-12-03 08:29 UTC
Labels: area/udp, bug, libslirp
