### ISSUE TITLE
[IPv6] Inconsistency in --disable-host-loopback

### ISSUE THREAD

**Issue by nertpinx** [rootless-containers/slirp4netns#93] opened 2019-06-20 15:22 UTC
I have local DNS forwarder set up. That means I have `nameserver ::1` in `/etc/hosts`. When I do:
``` bash
unshare --user --net
echo $$
```
then outside unshare:
``` bash
slirp4netns --configure $the_pid_from_above tap0
```

The processes in the container can resolve domain names using the provided DNS (`10.0.2.3`):
```
$ dig asdf.com @10.0.2.3

; <<>> DiG 9.12.3-P4 <<>> asdf.com @10.0.2.3
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38467
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;asdf.com.                      IN      A

;; ANSWER SECTION:
asdf.com.               14400   IN      A       64.90.40.65

;; Query time: 106 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Thu Jun 20 16:46:39 CEST 2019
;; MSG SIZE  rcvd: 53
```

But if I add `--disable-host-loopback`, the output varies.  The output on my machine (Gentoo) is:
```
$ dig asdf.com @10.0.2.3

; <<>> DiG 9.12.3-P4 <<>> asdf.com @10.0.2.3
;; global options: +cmd
;; connection timed out; no servers could be reached
```

On Fedora 30 it still works, which I believe should be the case as `--disable-host-loopback` should disable local access from the container using the `10.0.2.2` IP address, but not the connection from the dns forwarder.

I traced this to the fact that the setup on Fedora (using systemd-resolved) is using 127.0.0.53 whereas I am using `::1` or `127.0.0.1` **even though they all point to localhost** as all `127.0.0.0/8` addresses (if I put `nameserver 127.0.0.53` in my `resolv.conf`, it works).

Either I am right and I should be able to keep `nameserver ::1` in my `/etc/resolv.conf` **OR** I misunderstood the purpose of that option and this should not even work with `127.0.0.53`. Please tell me it is the former :wink:.

**Comment by AkihiroSuda** [comment] 2019-06-20 18:13
Thanks for the report, I think this is a bug.

> if I put nameserver 127.0.0.53 in my resolv.conf, it works

Does 127.0.0.1 work?

**Comment by nertpinx** [comment] 2019-06-21 08:07
@AkihiroSuda you know what? I thought I tried that and I haven't, apparently. Because 127.0.0.1 works now that I tried it again. So do you think it is just an IPv6 issue? I tried the original scenario with `-6` and it did not help.

**Comment by nertpinx** [comment] 2019-06-21 08:13
I also tried having both v6 and v4 localhost addresses (in this order) in the resolv.conf and it still works:
```
nameserver ::1
nameserver 127.0.0.1
```
So unless you feel like `::1` is something to be dealt with, you can close this issue.  Having this setup is completely acceptable for me, I just thought, for some reason, that it did not work either. Sorry for wasting your time and thanks for the tip.

**Comment by cryi** [comment] 2020-02-13 16:19
Hi @AkihiroSuda @nertpinx ,
during my testing of specific IP binding. I noticed this issue as well and it is not ipv6 limited - I am able to access host through 10.2.2.3 with `--disable-host-loopback`. (Ubuntu 18.04)

**Comment by 5eraph** [comment] 2020-02-13 16:22
Hi @nertpinx, @AkihiroSuda, 
I noticed this as well. I am able to access host loopback through 10.0.2.3 with `--disable-host-loopback`. (Ubuntu 18.04) so this is not ipv6 limited.

**Comment by 5eraph** [comment] 2020-02-13 19:05
Alright I was able to test the code and the issue is libslirp related. There is code which bypasses `--disable-host-loopback` [here for ipv4](https://github.com/rootless-containers/slirp4netns/blob/master/vendor/libslirp/src/socket.c#L836-L841) and [here for ipv6](https://github.com/rootless-containers/slirp4netns/blob/master/vendor/libslirp/src/socket.c#L857-L863).

**Comment by AkihiroSuda** [comment] 2020-02-14 02:43
@5eraph Expected behavior: https://github.com/rootless-containers/slirp4netns/blob/v0.4.3/slirp4netns.1.md#filtering-connections

**Comment by 5eraph** [comment] 2020-02-14 05:16
Alright well. Even tho it is expected, is it correct?
It breaks isolation of container and requires additional configuration outside of kube/docker-compose templates. I would rather prefer this to disable loopback fullyas one would expect. Or at least disable all ports except 53.

Anyway if this is expected, then this is not a bug and this issue may need another label?

**Comment by AkihiroSuda** [comment] 2020-02-14 05:27
Attack is realistic only if `/etc/resolv.conf` points to `127.0.0.1`. (OTOH it is typically `127.0.0.53` on systemd-based systems, so probably you are not affected)

> Edit: In case we fix/edit this in libslirp... do you think it can potentially break behavior of existing apps using slirp4net? (I consider whether to introduce --disable-local-dns or block everything with disabled loopback or disable everything except 53.

SGTM, do you want to send PR? (https://gitlab.freedesktop.org/slirp/libslirp)

cc @giuseppe @elmarco

**Comment by 5eraph** [comment] 2020-02-14 05:51
Yes, will do. Just which option do you prefer. Technically we can do both - limit 10.0.2.3 to port 53 by default and make it possible to disable it with `--disable-local-dns`. 

I will try to get this merged with specific IP binding, (around same time) To simplify merge from vendor.

**Comment by AkihiroSuda** [comment] 2020-02-14 05:53
>  limit 10.0.2.3 to port 53 by default and make it possible to disable it with --disable-local-dns.

SGTM

**Comment by 5eraph** [comment] 2020-02-14 16:03
I created issue for this [here](https://gitlab.freedesktop.org/slirp/libslirp/issues/16) in libslirp repository.

**Comment by 5eraph** [comment] 2020-04-19 09:14
Fix for this is already merged in libslirp repository and should be included in next release libslirp release.

**Closed** 2020-04-19 09:19 UTC
Labels: area/ipv6, bug
